# File @generated by Olwethu Ngxatu DO NOT EDIT.
# This file lists all contributors to the repository.
# See Olwethu Ngxatu to make modifications.

Athandwe Ndlebe <athandwe@gmail.com>
Libo Hlangwini <libonmu@gmail.com>
Phuti Nkuna <pnkuna@gmail.com>
Dillian Immanuel <dimmanuel@gmail.com>
